/**
 * ============================================================
 * PAYROLL PORTAL API - GOOGLE APPS SCRIPT
 * ============================================================
 *
 * Google Spreadsheet must contain:
 *
 * 1) Users
 * Username | EmployeeID | FullName | PasswordHash | PasswordSalt |
 * MustChangePassword | Active | UpdatedAt
 *
 * 2) Salary
 * PayMonth | Factory | UpdatedAt | EmployeeID | FullName | CitizenID |
 * Department | Section | Position | TotalIncome | MonthlySalary |
 * BasicSalary | WorkingDays | HolidayDays | PaidLeaveDays |
 * UnpaidLeaveDays | RegionalMinimumLeaveDays | OvertimePay |
 * OvertimeHours | RestDayHours | OvertimeRestDayHours |
 * NightRestDayOvertimeHours | HolidayHours | HolidayOvertimeHours |
 * NightHolidayOvertimeHours | NightShiftDays | NightOvertimeHours |
 * OtherMoney | Discipline | Loyalty2Years | Loyalty5Years | Loyalty10Years |
 * Housing | Transportation | AttendanceBonus | SalesCommissionBonus |
 * SeveranceUnusedLeave | SocialInsurance | HealthInsurance |
 * UnemploymentInsurance | PersonalIncomeTax | Advance | OtherDeductions |
 * NetPay
 *
 * 3) SyncLog (optional; created automatically)
 *
 * Deploy:
 * Execute as: Me
 * Who has access: Anyone
 *
 * Script Properties:
 * SPREADSHEET_ID   = Spreadsheet ID (recommended when script is standalone)
 * SYNC_API_KEY     = long random secret used by VBA
 * ADMIN_PASSWORD_HASH = generated by setupAdmin()
 * ============================================================
 */

const CFG = {
  USERS: 'Users',
  SALARY: 'Salary',
  SYNC_LOG: 'SyncLog',
  TZ: 'Asia/Ho_Chi_Minh',
  SESSION_SECONDS: 1800,
  MIN_PASSWORD_LENGTH: 8
};

const SALARY_HEADERS = [
  'PayMonth','Factory','UpdatedAt','EmployeeID','FullName','CitizenID',
  'Department','Section','Position','TotalIncome','MonthlySalary',
  'BasicSalary','WorkingDays','HolidayDays','PaidLeaveDays',
  'UnpaidLeaveDays','RegionalMinimumLeaveDays','OvertimePay',
  'OvertimeHours','RestDayHours','OvertimeRestDayHours',
  'NightRestDayOvertimeHours','HolidayHours','HolidayOvertimeHours',
  'NightHolidayOvertimeHours','NightShiftDays','NightOvertimeHours',
  'OtherMoney','Discipline','Loyalty2Years','Loyalty5Years',
  'Loyalty10Years','Housing','Transportation','AttendanceBonus',
  'SalesCommissionBonus','SeveranceUnusedLeave','SocialInsurance',
  'HealthInsurance','UnemploymentInsurance','PersonalIncomeTax',
  'Advance','OtherDeductions','NetPay'
];

const USER_HEADERS = [
  'Username','EmployeeID','FullName','PasswordHash','PasswordSalt',
  'MustChangePassword','Active','UpdatedAt'
];

function doGet(e) {
  return json_({ok:true, service:'Payroll Portal API', version:'2.0'});
}

function doPost(e) {
  try {
    const b = JSON.parse((e && e.postData && e.postData.contents) || '{}');
    switch (String(b.action || '')) {
      case 'login': return json_(login_(b));
      case 'changePassword': return json_(changePassword_(b));
      case 'getPayslip': return json_(getPayslip_(b));
      case 'adminLogin': return json_(adminLogin_(b));
      case 'adminReset': return json_(adminReset_(b));
      case 'syncPayroll': return json_(syncPayroll_(b));
      case 'health': return json_({ok:true});
      default: return json_({ok:false,error:'ACTION_NOT_SUPPORTED'});
    }
  } catch (err) {
    console.error(err);
    return json_({
      ok:false,
      error:String(err && err.message ? err.message : err)
    });
  }
}

/* =========================
   AUTH
   ========================= */

function login_(b) {
  const username = normalizeId_(b.username);
  const password = String(b.password || '');
  if (!username || !password) return {ok:false,error:'MISSING_LOGIN'};

  const user = findUser_(username);
  if (!user || !truth_(user.Active)) {
    return {ok:false,error:'INVALID_LOGIN'};
  }

  if (!verifyPassword_(password, user.PasswordHash, user.PasswordSalt)) {
    return {ok:false,error:'INVALID_LOGIN'};
  }

  const token = createSession_('user', username);

  return {
    ok:true,
    token:token,
    mustChangePassword:truth_(user.MustChangePassword),
    user:{
      username:username,
      employeeId:String(user.EmployeeID || ''),
      fullName:String(user.FullName || '')
    }
  };
}

function changePassword_(b) {
  const session = requireSession_(b.token, 'user');
  const password = String(b.newPassword || '');

  if (password.length < CFG.MIN_PASSWORD_LENGTH) {
    return {
      ok:false,
      error:'PASSWORD_TOO_SHORT',
      min:CFG.MIN_PASSWORD_LENGTH
    };
  }

  const sheet = getSheet_(CFG.USERS);
  const data = sheet.getDataRange().getValues();
  if (data.length < 2) return {ok:false,error:'USER_NOT_FOUND'};

  const idx = headerMap_(data[0]);
  const salt = randomSalt_();
  const hash = hashPassword_(password, salt);

  for (let r=1; r<data.length; r++) {
    if (normalizeId_(data[r][idx.Username]) === session.username) {
      sheet.getRange(r+1, idx.PasswordHash+1).setValue(hash);
      sheet.getRange(r+1, idx.PasswordSalt+1).setValue(salt);
      sheet.getRange(r+1, idx.MustChangePassword+1).setValue(false);
      sheet.getRange(r+1, idx.UpdatedAt+1).setValue(now_());
      return {ok:true};
    }
  }

  return {ok:false,error:'USER_NOT_FOUND'};
}

/* =========================
   PAYSLIP
   ========================= */

function getPayslip_(b) {
  const session = requireSession_(b.token, 'user');
  const month = String(b.month || '');

  if (!/^\d{2}-\d{4}$/.test(month)) {
    return {ok:false,error:'INVALID_MONTH'};
  }

  const user = findUser_(session.username);
  if (!user) return {ok:false,error:'USER_NOT_FOUND'};

  const employeeId = String(user.EmployeeID || '');
  const sheet = getSheet_(CFG.SALARY);
  const data = sheet.getDataRange().getValues();

  if (data.length < 2) return {ok:false,error:'NO_DATA'};

  const idx = headerMap_(data[0]);
  let found = null;

  for (let r=1; r<data.length; r++) {
    const row = data[r];

    if (
      String(row[idx.EmployeeID] || '') === employeeId &&
      String(row[idx.PayMonth] || '') === month
    ) {
      found = objectFromRow_(data[0], row);
      break;
    }
  }

  if (!found) return {ok:false,error:'PAYSLIP_NOT_FOUND'};

  return {
    ok:true,
    payslip:{
      month:month,
      factory:String(found.Factory || ''),
      updatedAt:String(found.UpdatedAt || ''),
      employee:{
        employeeId:String(found.EmployeeID || ''),
        fullName:String(found.FullName || ''),
        citizenId:String(found.CitizenID || ''),
        department:String(found.Department || ''),
        section:String(found.Section || ''),
        position:String(found.Position || '')
      },
      income:{
        totalIncome:n_(found.TotalIncome),
        monthlySalary:n_(found.MonthlySalary),
        basicSalary:n_(found.BasicSalary),
        workingDays:n_(found.WorkingDays),
        holidayDays:n_(found.HolidayDays),
        paidLeaveDays:n_(found.PaidLeaveDays),
        unpaidLeaveDays:n_(found.UnpaidLeaveDays),
        regionalMinimumLeaveDays:n_(found.RegionalMinimumLeaveDays),
        overtimePay:n_(found.OvertimePay),
        overtimeHours:n_(found.OvertimeHours),
        restDayHours:n_(found.RestDayHours),
        overtimeRestDayHours:n_(found.OvertimeRestDayHours),
        nightRestDayOvertimeHours:n_(found.NightRestDayOvertimeHours),
        holidayHours:n_(found.HolidayHours),
        holidayOvertimeHours:n_(found.HolidayOvertimeHours),
        nightHolidayOvertimeHours:n_(found.NightHolidayOvertimeHours),
        nightShiftDays:n_(found.NightShiftDays),
        nightOvertimeHours:n_(found.NightOvertimeHours),
        otherMoney:n_(found.OtherMoney),
        discipline:n_(found.Discipline),
        loyalty2Years:n_(found.Loyalty2Years),
        loyalty5Years:n_(found.Loyalty5Years),
        loyalty10Years:n_(found.Loyalty10Years),
        housing:n_(found.Housing),
        transportation:n_(found.Transportation),
        attendanceBonus:n_(found.AttendanceBonus),
        salesCommissionBonus:n_(found.SalesCommissionBonus),
        severanceUnusedLeave:n_(found.SeveranceUnusedLeave)
      },
      deductions:{
        socialInsurance:n_(found.SocialInsurance),
        healthInsurance:n_(found.HealthInsurance),
        unemploymentInsurance:n_(found.UnemploymentInsurance),
        personalIncomeTax:n_(found.PersonalIncomeTax),
        advance:n_(found.Advance),
        otherDeductions:n_(found.OtherDeductions)
      },
      netPay:n_(found.NetPay)
    }
  };
}

/* =========================
   ADMIN
   ========================= */

function setupAdmin() {
  // CHỈ chạy thủ công trong Apps Script.
  // Sau khi tạo hash, xóa/đổi mật khẩu và không public log.
  const password = Browser.inputBox('Nhập mật khẩu Admin');
  if (!password || password === 'cancel') return;

  const salt = randomSalt_();
  const hash = hashPassword_(password, salt);

  PropertiesService.getScriptProperties().setProperties({
    ADMIN_PASSWORD_HASH: hash,
    ADMIN_PASSWORD_SALT: salt
  });

  Logger.log('ADMIN_PASSWORD_HASH=' + hash);
  Logger.log('ADMIN_PASSWORD_SALT=' + salt);
}

function adminLogin_(b) {
  const password = String(b.password || '');
  const props = PropertiesService.getScriptProperties();

  const hash = props.getProperty('ADMIN_PASSWORD_HASH') || '';
  const salt = props.getProperty('ADMIN_PASSWORD_SALT') || '';

  if (!hash || !salt || !verifyPassword_(password, hash, salt)) {
    return {ok:false,error:'INVALID_ADMIN_LOGIN'};
  }

  return {
    ok:true,
    token:createSession_('admin','admin')
  };
}

function adminReset_(b) {
  requireSession_(b.token, 'admin');

  const username = normalizeId_(b.username);
  if (!username) return {ok:false,error:'MISSING_USERNAME'};

  const sheet = getSheet_(CFG.USERS);
  const data = sheet.getDataRange().getValues();
  if (data.length < 2) return {ok:false,error:'USER_NOT_FOUND'};

  const idx = headerMap_(data[0]);

  for (let r=1; r<data.length; r++) {
    if (normalizeId_(data[r][idx.Username]) === username) {
      const employeeId = String(data[r][idx.EmployeeID] || '');

      if (!employeeId) {
        return {ok:false,error:'EMPLOYEE_ID_EMPTY'};
      }

      const salt = randomSalt_();
      const hash = hashPassword_(employeeId, salt);

      sheet.getRange(r+1, idx.PasswordHash+1).setValue(hash);
      sheet.getRange(r+1, idx.PasswordSalt+1).setValue(salt);
      sheet.getRange(r+1, idx.MustChangePassword+1).setValue(true);
      sheet.getRange(r+1, idx.UpdatedAt+1).setValue(now_());

      return {
        ok:true,
        resetToEmployeeId:true
      };
    }
  }

  return {ok:false,error:'USER_NOT_FOUND'};
}

/* =========================
   SYNC FROM VBA
   ========================= */

function syncPayroll_(b) {
  const expectedKey =
    PropertiesService.getScriptProperties().getProperty('SYNC_API_KEY') || '';

  if (!expectedKey || String(b.apiKey || '') !== expectedKey) {
    return {ok:false,error:'INVALID_SYNC_KEY'};
  }

  const factory = String(b.factory || '');
  const payMonth = String(b.payMonth || '');
  const rows = Array.isArray(b.rows) ? b.rows : [];

  if (!['Snack','Flexible'].includes(factory)) {
    return {ok:false,error:'INVALID_FACTORY'};
  }

  if (!/^\d{2}-\d{4}$/.test(payMonth)) {
    return {ok:false,error:'INVALID_MONTH'};
  }

  if (!rows.length) return {ok:false,error:'NO_ROWS'};

  const sheet = getSheet_(CFG.SALARY);
  ensureHeaders_(sheet, SALARY_HEADERS);

  // Xóa kỳ cũ của đúng xưởng + tháng.
  const data = sheet.getDataRange().getValues();
  const idx = headerMap_(data[0]);

  for (let r=data.length-1; r>=1; r--) {
    if (
      String(data[r][idx.Factory] || '') === factory &&
      String(data[r][idx.PayMonth] || '') === payMonth
    ) {
      sheet.deleteRow(r+1);
    }
  }

  const updated = now_();
  const out = rows.map(x =>
    SALARY_HEADERS.map(h => {
      if (h === 'PayMonth') return payMonth;
      if (h === 'Factory') return factory;
      if (h === 'UpdatedAt') return updated;
      return x[h] !== undefined ? x[h] : '';
    })
  );

  if (out.length) {
    sheet
      .getRange(sheet.getLastRow()+1,1,out.length,SALARY_HEADERS.length)
      .setValues(out);
  }

  syncUsers_(rows);
  logSync_(factory,payMonth,out.length,'OK');

  return {
    ok:true,
    factory:factory,
    payMonth:payMonth,
    rows:out.length,
    updatedAt:updated
  };
}

function syncUsers_(rows) {
  const sheet = getSheet_(CFG.USERS);
  ensureHeaders_(sheet, USER_HEADERS);

  const data = sheet.getDataRange().getValues();
  const idx = headerMap_(data[0]);
  const map = {};

  for (let r=1; r<data.length; r++) {
    const username = normalizeId_(data[r][idx.Username]);
    if (username) map[username] = r+1;
  }

  rows.forEach(x => {
    const citizenId = normalizeId_(x.CitizenID);
    if (!citizenId) return;

    const employeeId = String(x.EmployeeID || '');
    const fullName = String(x.FullName || '');

    if (!map[citizenId]) {
      const salt = randomSalt_();

      const row = USER_HEADERS.map(h => {
        if (h === 'Username') return citizenId;
        if (h === 'EmployeeID') return employeeId;
        if (h === 'FullName') return fullName;
        if (h === 'PasswordSalt') return salt;
        if (h === 'PasswordHash') return hashPassword_(employeeId,salt);
        if (h === 'MustChangePassword') return true;
        if (h === 'Active') return true;
        if (h === 'UpdatedAt') return now_();
        return '';
      });

      sheet.appendRow(row);
      map[citizenId] = sheet.getLastRow();
    } else {
      const rr = map[citizenId];

      sheet.getRange(rr,idx.EmployeeID+1).setValue(employeeId);
      sheet.getRange(rr,idx.FullName+1).setValue(fullName);
      sheet.getRange(rr,idx.Active+1).setValue(true);
      sheet.getRange(rr,idx.UpdatedAt+1).setValue(now_());

      // Không reset password khi sync dữ liệu lương.
    }
  });
}

/* =========================
   HELPERS
   ========================= */

function getSS_() {
  const id = PropertiesService.getScriptProperties().getProperty('SPREADSHEET_ID');
  return id ? SpreadsheetApp.openById(id) : SpreadsheetApp.getActiveSpreadsheet();
}

function getSheet_(name) {
  const sheet = getSS_().getSheetByName(name);
  if (!sheet) throw new Error('Missing sheet: ' + name);
  return sheet;
}

function ensureHeaders_(sheet, headers) {
  if (sheet.getLastRow() === 0) {
    sheet.getRange(1,1,1,headers.length).setValues([headers]);
    return;
  }

  const current = sheet.getRange(1,1,1,headers.length).getValues()[0];
  let mismatch = false;

  for (let i=0;i<headers.length;i++) {
    if (String(current[i] || '') !== headers[i]) {
      mismatch = true;
      break;
    }
  }

  if (mismatch) {
    throw new Error(
      'Header sheet "'+sheet.getName()+'" không đúng. ' +
      'Hãy tạo đúng header theo README.'
    );
  }
}

function findUser_(username) {
  const sheet = getSheet_(CFG.USERS);
  const data = sheet.getDataRange().getValues();
  if (data.length < 2) return null;

  const idx = headerMap_(data[0]);

  for (let r=1;r<data.length;r++) {
    if (normalizeId_(data[r][idx.Username]) === username) {
      return objectFromRow_(data[0],data[r]);
    }
  }

  return null;
}

function createSession_(role,username) {
  const token = Utilities.getUuid();

  CacheService.getScriptCache().put(
    'SESSION_' + token,
    JSON.stringify({
      role:role,
      username:username,
      created:Date.now()
    }),
    CFG.SESSION_SECONDS
  );

  return token;
}

function requireSession_(token,role) {
  if (!token) throw new Error('UNAUTHORIZED');

  const raw =
    CacheService.getScriptCache().get('SESSION_' + String(token));

  if (!raw) throw new Error('SESSION_EXPIRED');

  const s = JSON.parse(raw);

  if (s.role !== role) throw new Error('FORBIDDEN');

  return s;
}

function hashPassword_(password,salt) {
  return sha256_(String(salt) + ':' + String(password));
}

function verifyPassword_(password,hash,salt) {
  if (!hash || !salt) return false;
  return hashPassword_(password,salt) === String(hash);
}

function randomSalt_() {
  return Utilities.getUuid().replace(/-/g,'') +
         Utilities.getUuid().replace(/-/g,'');
}

function sha256_(text) {
  const bytes = Utilities.computeDigest(
    Utilities.DigestAlgorithm.SHA_256,
    String(text),
    Utilities.Charset.UTF_8
  );

  return bytes.map(b => {
    const v = (b < 0 ? b + 256 : b).toString(16);
    return v.length === 1 ? '0' + v : v;
  }).join('');
}

function normalizeId_(v) {
  return String(v == null ? '' : v)
    .trim()
    .replace(/^'/,'');
}

function n_(v) {
  if (v === '' || v == null) return 0;
  const n = Number(v);
  return isNaN(n) ? 0 : n;
}

function truth_(v) {
  return v === true ||
    String(v).toLowerCase() === 'true' ||
    String(v) === '1';
}

function now_() {
  return Utilities.formatDate(
    new Date(),
    CFG.TZ,
    'dd/MM/yyyy HH:mm:ss'
  );
}

function headerMap_(headers) {
  const m = {};
  headers.forEach((h,i) => m[String(h).trim()] = i);
  return m;
}

function objectFromRow_(headers,row) {
  const o = {};
  headers.forEach((h,i) => o[String(h).trim()] = row[i]);
  return o;
}

function logSync_(factory,payMonth,rows,status) {
  const ss = getSS_();
  let sheet = ss.getSheetByName(CFG.SYNC_LOG);

  if (!sheet) {
    sheet = ss.insertSheet(CFG.SYNC_LOG);
    sheet.appendRow([
      'UpdatedAt','Factory','PayMonth','Rows','Status'
    ]);
  }

  sheet.appendRow([
    now_(),factory,payMonth,rows,status
  ]);
}

function json_(obj) {
  return ContentService
    .createTextOutput(JSON.stringify(obj))
    .setMimeType(ContentService.MimeType.JSON);
}
